# msm8x60
obj-$(CONFIG_MACH_PYRAMID) += pyramid-panel.o
obj-$(CONFIG_MACH_SHOOTER) += shooter-panel.o
obj-$(CONFIG_MACH_SHOOTER_U) += shooter_u-panel.o
obj-$(CONFIG_MACH_SHOOTER_K) += shooter_k-panel.o
obj-$(CONFIG_MACH_SHOOTER_CT) += shooter_ct-panel.o
obj-$(CONFIG_MACH_RIDER) += rider-panel.o
obj-$(CONFIG_MACH_VILLEC2) += board-villec2-panel.o
obj-$(CONFIG_MACH_HOLIDAY) += holiday-panel.o
obj-$(CONFIG_MACH_VIGOR) += vigor-panel.o
obj-$(CONFIG_MACH_RUBY) += ruby-panel.o
# msm8960
obj-$(CONFIG_MACH_VILLE) += board-ville-panel.o board-ville-display.o
obj-$(CONFIG_MACH_ELITE) += board-elite-display.o board-elite-panel.o
obj-$(CONFIG_MACH_JET) += board-jet-panel.o
obj-$(CONFIG_MACH_JEWEL_DD) += board-jel_dd-panel.o
obj-$(CONFIG_MACH_EVITA_UTL) += board-evita_utl-display.o board-evita_utl-panel.o
obj-$(CONFIG_MACH_FIGHTER) += board-fighter-panel.o
obj-$(CONFIG_MACH_VALENTE_WX) += board-valente_wx-panel.o board-valente_wx-display.o
obj-$(CONFIG_MACH_VALENTE_WX_C9) += board-valente_wx-panel.o board-valente_wx-display.o
