GCC_VERSION      := $(shell $(CONFIG_SHELL) $(PWD)/scripts/gcc-version.sh $(CROSS_COMPILE)gcc)
obj-$(CONFIG_RAWCHIP) += rawchip_spi.o rawchip.o Yushan_API.o Yushan_Platform_Specific.o Yushan_HTC_Functions.o
obj-$(CONFIG_RAWCHIP) += yushan_reg.o yushan_u_code_r2.o yushan_u_code_r3.o yushan_reg_s5k3h2yx.o yushan_reg_imx175.o yushan_reg_ov8838.o yushan_reg_ar0260.o yushan_reg_ov2722.o yushan_reg_ov5693.o yushan_reg_s5k6a2ya.o
