#
# Makefile for TI's shared transport line discipline
# and its protocol drivers (BT, FM, GPS)
#
obj-$(CONFIG_FPR_SPI)	+= vfsSpiDrv.o

EXTRA_CFLAGS += -DPLATFORM_BIG_ENDIAN=1 -DVCS_FEATURE_SENSOR_WINDSOR=0
