# Makefile for the htc stability mechanism.
#

obj-$(CONFIG_DIRTY_SYSTEM_DETECTOR) += dirty_file_detector.o
obj-$(CONFIG_HTC_DEBUG_SEND_SIGNAL) += send_signal_debug.o

# bootmsg
obj-$(CONFIG_HTC_DEBUG_SAVE_BOOT_MSG) += bootmsg.o
