#
# Makefile for the HTC board
#

# ELITE
obj-$(CONFIG_MACH_ELITE) += elite/

# FIGHTER
obj-$(CONFIG_MACH_FIGHTER) += fighter/

# JET
obj-$(CONFIG_MACH_JET) += jet/

# VILLE
obj-$(CONFIG_MACH_VILLE) += ville/
